services:
  docs:
    image: pet_ecommerce_django_drf_local_docs
    container_name: pet_ecommerce_django_drf_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./pet_ecommerce_django_drf:/app/pet_ecommerce_django_drf:z
    ports:
      - '9000:9000'
    command: /start-docs
