[project]
name = "pet-ecommerce-django-drf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-rest-framework>=0.1.0",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
